---

- name: "3.1.1 | PATCH | Disable IPv6"
  block:
      - name: "3.1.1 | AUDIT | Disable IPv6 | Get current GRUB_CMDLINE_LINUX settings"
        shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_3_1_1_grub_cmdline_linux_settings

      - name: "3.1.1 | PATCH | Disable IPv6 | Add ipv6.disable if does not exist"
        lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX'
            line: 'GRUB_CMDLINE_LINUX="{{ ubtu22cis_3_1_1_grub_cmdline_linux_settings.stdout }} ipv6.disable=1"'
        when: "'ipv6.disable' not in ubtu22cis_3_1_1_grub_cmdline_linux_settings.stdout"
        notify: grub update

      - name: "3.1.1 | PATCH | Disable IPv6 | Set ipv6.disable to 1 if exists"
        replace:
            path: /etc/default/grub
            regexp: 'ipv6\.disable=.'
            replace: 'ipv6.disable=1'
        when: "'ipv6.disable' in ubtu22cis_3_1_1_grub_cmdline_linux_settings.stdout"
        notify: grub update

      - name: "3.1.1 | PATCH | Disable IPv6 | Remove net.ipv6.conf.all.disable_ipv6"
        lineinfile:
            path: /etc/sysctl.conf
            regexp: '^net.ipv6.conf.all.disable_ipv6.*'
            state: absent
  when:
      - ubtu22cis_rule_3_1_1
      - not ubtu22cis_ipv6_required
  tags:
      - level2-server
      - level2-workstation
      - manual
      - patch
      - rule_3.1.1
      - ipv6

- name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  block:
      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Check for network-manager tool"
        shell: nmcli radio wifi
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_3_1_2_wifi_status
        when: "'network-manager' in ansible_facts.packages"

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Warn about wireless if network-manager not installed"
        debug:
            msg: "Warning!! You need to disable wireless interfaces manually since network-manager is not installed"
        when: "'network-manager' not in ansible_facts.packages"

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Set warning count"
        set_fact:
            control_number: "{{ control_number }} + [ 'rule_3.1.2' ]"
            warn_count: "{{ warn_count | int +1 }}"
        when: "'network-manager' not in ansible_facts.packages"

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Disable wireless if network-manager installed"
        command: nmcli radio all off
        changed_when: ubtu22cis_3_1_2_nmcli_radio_off.rc == 0
        register: ubtu22cis_3_1_2_nmcli_radio_off
        when:
            - "'network-manager' in ansible_facts.packages"
            - "'enabled' in ubtu22cis_3_1_2_wifi_status.stdout"
  when:
      - ubtu22cis_rule_3_1_2
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_3.1.2
      - wireless
